#!/bin/bash -ex


pushd $(dirname $0) > /dev/null 2>&1;

THEME_ROOT="$(PWD)/.theme";
THEME_LINK="$(PWD)/src/htdocs/theme";


rm -rf $THEME_ROOT;
npm install hazdev-template;

mv node_modules/hazdev-template/dist $THEME_ROOT;
rm -rf node_modules

unlink $THEME_LINK;
ln -sf $THEME_ROOT/htdocs $THEME_LINK;

cat <<-EOF > php.ini
;; autogenerated at $(date)

; add template lib directory to include path
include_path = '.:${THEME_ROOT}/lib'
EOF


popd > /dev/null 2>&1;


exit 0;
