#!/bin/bash -ex


pushd $(dirname $0) > /dev/null 2>&1;

THEME_ROOT="$(pwd)/.theme";
THEME_LINK="$(pwd)/src/htdocs/theme";


rm -rf $THEME_ROOT;
npm install --no-save hazdev-template;
if [ -f package-lock.json ]; then
  rm -f package-lock.json;
fi

mv node_modules/hazdev-template/dist $THEME_ROOT;
rm -rf node_modules

if [ -L $THEME_LINK ]; then
  unlink $THEME_LINK;
fi

ln -sf $THEME_ROOT/htdocs $THEME_LINK;

cat <<-EOF > php.ini
;; autogenerated at $(date)

; add template lib directory to include path
include_path = '.:$(pwd):${THEME_ROOT}/lib'
EOF


popd > /dev/null 2>&1;


exit 0;
